/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package index;

import aplikasizakat.formAbout;
import aplikasizakat.mainZakat;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SpinnerNumberModel;
import java.util.Scanner;
/**
 *
 * @author abdul hamid
 */

public class index extends javax.swing.JFrame {

    public static mainZakat mainZakat;
    static mainZakat main=new mainZakat();
    SpinnerNumberModel jmlJiwa;
    public static Double totalBayar;
    Integer nilai=0;
    Integer terendah=0;
    Integer tertinggi=30;
    Integer maju=1;
    static String[] angkaTerbilang={"","Satu","Dua","Tiga","Empat","Lima","Enam","Tujuh","Delapan","Sembilan","Sepuluh","Sebelas"};
    public index() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jTInformasi.setText("Besar zakat fitrah yang harus dibayarkan berdasarkan pada jenis beras yang selalu dikonsumsi sehari hari");
        jTInformasi.setBackground(Color.cyan);
        jTInformasi.setForeground(Color.red);
        jmlJiwa=new SpinnerNumberModel(nilai,terendah,tertinggi,maju);
        spnJiwa.setModel(jmlJiwa);
        
    }
public static String angkaToTerbilang(Double angka){
if(angka < 12.0)
return angkaTerbilang[angka.intValue()];
if(angka >=12.0 && angka <= 19.0)
return angkaTerbilang[angka.intValue() % 10] + " Belas";
if(angka >= 20.0 && angka <= 99.0)
return angkaToTerbilang(angka / 10) + " Puluh " + angkaTerbilang[angka.intValue() % 10];
if(angka >= 100.0 && angka <= 199.0)
return "Seratus " + angkaToTerbilang(angka % 100);
if(angka >= 200.0 && angka <= 999.0)
return angkaToTerbilang(angka / 100) + " Ratus " + angkaToTerbilang(angka % 100);
if(angka >= 1000.0 && angka <= 1999.0)
return "Seribu " + angkaToTerbilang(angka % 1000);
if(angka >= 2000.0 && angka <= 999999.0)
return angkaToTerbilang(angka / 1000) + " Ribu " + angkaToTerbilang(angka % 1000);
if(angka >= 1000000.0 && angka <= 999999999.0)
return angkaToTerbilang(angka / 1000000) + " Juta " + angkaToTerbilang(angka % 1000000);
if(angka >= 1000000000.0 && angka <= 999999999999L)
return angkaToTerbilang(angka / 1000000000) + " Milyar " + angkaToTerbilang(angka % 1000000000);

return "";
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblInputMuzakki = new javax.swing.JLabel();
        lblDaftarMuzakki = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblInputMustahiq = new javax.swing.JLabel();
        lblDaftarMustahiq = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTInformasi = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        txtBeras = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtTotalZakat = new javax.swing.JTextField();
        txtZakat = new javax.swing.JTextField();
        spnJiwa = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTerbilang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnAbout = new javax.swing.JMenu();
        mnKeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEM INFORMASI ZAKAT FITRAH");
        setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEM INFORMASI ZAKAT FITRAH");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MASJID ALMUHAJIRIN");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTabbedPane1.setForeground(new java.awt.Color(204, 0, 0));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        lblInputMuzakki.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        lblInputMuzakki.setText("INPUT DATA MUZAKKI");
        lblInputMuzakki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInputMuzakki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInputMuzakkiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInputMuzakkiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInputMuzakkiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblInputMuzakkiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblInputMuzakkiMouseReleased(evt);
            }
        });

        lblDaftarMuzakki.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        lblDaftarMuzakki.setText("DAFTAR MUZAKKI");
        lblDaftarMuzakki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDaftarMuzakki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDaftarMuzakkiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDaftarMuzakkiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDaftarMuzakkiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDaftarMuzakkiMousePressed(evt);
            }
        });

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblDaftarMuzakki)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblInputMuzakki)
                        .addContainerGap(1228, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInputMuzakki)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblDaftarMuzakki, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Penerimaan Muzakki", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));

        lblInputMustahiq.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        lblInputMustahiq.setText("INPUT DATA MUSTAHIQ");
        lblInputMustahiq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInputMustahiq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInputMustahiqMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInputMustahiqMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInputMustahiqMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblInputMustahiqMousePressed(evt);
            }
        });

        lblDaftarMustahiq.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        lblDaftarMustahiq.setText("DAFTAR MUSTAHIQ");
        lblDaftarMustahiq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDaftarMustahiq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDaftarMustahiqMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDaftarMustahiqMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDaftarMustahiqMouseExited(evt);
            }
        });

        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDaftarMustahiq)
                    .addComponent(lblInputMustahiq))
                .addContainerGap(1214, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInputMustahiq)
                    .addComponent(jLabel12))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(lblDaftarMustahiq))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Penyaluran Mustahiq", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Informasi"));

        jTInformasi.setEditable(false);
        jTInformasi.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(jTInformasi);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("HARGA BERAS PER KG");

        txtBeras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBeras.setForeground(new java.awt.Color(153, 0, 0));
        txtBeras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBerasActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("BESAR ZAKAT FITRAH PERJIWA");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("JUMLAH JIWA");

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("JUMLAH ZAKAT FITRAH");

        txtTotalZakat.setEditable(false);
        txtTotalZakat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotalZakat.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(txtTotalZakat, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalZakat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap())
        );

        txtZakat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtZakat.setForeground(new java.awt.Color(153, 0, 0));
        txtZakat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtZakatMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtZakatMousePressed(evt);
            }
        });
        txtZakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZakatActionPerformed(evt);
            }
        });

        spnJiwa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnJiwaStateChanged(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("ORANG");

        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtTerbilang.setEditable(false);
        txtTerbilang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTerbilang.setForeground(new java.awt.Color(102, 0, 0));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("TERBILANG");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtTerbilang))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(spnJiwa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19))
                            .addComponent(txtZakat, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBeras, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 521, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBeras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtZakat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(spnJiwa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTerbilang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Kalkulator Zakat", jPanel3);

        mnAbout.setText("About");
        mnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAboutMouseClicked(evt);
            }
        });
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnAbout);

        mnKeluar.setText("Logout");
        mnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnKeluarMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnKeluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane1)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(321, 321, 321))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(363, 363, 363))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnKeluarMouseClicked
        // TODO add your handling code here:
        aplikasizakat.AplikasiZakat.isLogin(false);
        this.dispose();
        //main.setVisible(true);  
    }//GEN-LAST:event_mnKeluarMouseClicked

    private void lblInputMuzakkiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInputMuzakkiMouseEntered
        // TODO add your handling code here:
        lblInputMuzakki.setForeground(Color.red);
        
    }//GEN-LAST:event_lblInputMuzakkiMouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new muzakki.inputMuzakki().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void txtZakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZakatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZakatActionPerformed

    private void lblInputMuzakkiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInputMuzakkiMouseClicked
        // TODO add your handling code here:
        new muzakki.inputMuzakki().setVisible(true);
    }//GEN-LAST:event_lblInputMuzakkiMouseClicked

    private void txtZakatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtZakatMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZakatMouseEntered

    private void txtZakatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtZakatMousePressed
        // TODO add your handling code here:
        double hargaZakat=Integer.parseInt(txtBeras.getText())*2.5;
        txtZakat.setText(Double.toString(hargaZakat));
    }//GEN-LAST:event_txtZakatMousePressed

    private void spnJiwaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnJiwaStateChanged
        // TODO add your handling code here:
        
        
        double jiwaN=jmlJiwa.getNumber().doubleValue();
        totalBayar=jiwaN*Double.parseDouble(txtZakat.getText());
        txtTotalZakat.setText(Double.toString(totalBayar));
        
        //long sc=Long.parseLong(txtTotalZakat.getText());
        double totZakat=Double.parseDouble(txtTotalZakat.getText());
        Scanner input=new Scanner(System.in);
        txtTerbilang.setText(new index().angkaToTerbilang(totZakat)+" Rupiah");
    }//GEN-LAST:event_spnJiwaStateChanged

    private void lblDaftarMuzakkiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDaftarMuzakkiMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDaftarMuzakkiMousePressed

    private void lblDaftarMuzakkiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDaftarMuzakkiMouseClicked
        // TODO add your handling code here:
        new muzakki.datfarMuzakki().setVisible(true);
    }//GEN-LAST:event_lblDaftarMuzakkiMouseClicked

    private void lblInputMustahiqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInputMustahiqMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblInputMustahiqMouseClicked

    private void lblInputMustahiqMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInputMustahiqMousePressed
        // TODO add your handling code here:
        new mustahiq.inputMustahiq().setVisible(true);
    }//GEN-LAST:event_lblInputMustahiqMousePressed

    private void lblInputMuzakkiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInputMuzakkiMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblInputMuzakkiMousePressed

    private void lblInputMuzakkiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInputMuzakkiMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblInputMuzakkiMouseReleased

    private void lblInputMuzakkiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInputMuzakkiMouseExited
        // TODO add your handling code here:
        lblInputMuzakki.setForeground(Color.black);
    }//GEN-LAST:event_lblInputMuzakkiMouseExited

    private void lblDaftarMuzakkiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDaftarMuzakkiMouseEntered
        // TODO add your handling code here:
        lblDaftarMuzakki.setForeground(Color.red);
    }//GEN-LAST:event_lblDaftarMuzakkiMouseEntered

    private void lblDaftarMuzakkiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDaftarMuzakkiMouseExited
        // TODO add your handling code here:
        lblDaftarMuzakki.setForeground(Color.black);
    }//GEN-LAST:event_lblDaftarMuzakkiMouseExited

    private void lblInputMustahiqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInputMustahiqMouseEntered
        // TODO add your handling code here:
        lblInputMustahiq.setForeground(Color.red);
    }//GEN-LAST:event_lblInputMustahiqMouseEntered

    private void lblInputMustahiqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInputMustahiqMouseExited
        // TODO add your handling code here:
        lblInputMustahiq.setForeground(Color.black);
    }//GEN-LAST:event_lblInputMustahiqMouseExited

    private void lblDaftarMustahiqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDaftarMustahiqMouseEntered
        // TODO add your handling code here:
        lblDaftarMustahiq.setForeground(Color.red);
    }//GEN-LAST:event_lblDaftarMustahiqMouseEntered

    private void lblDaftarMustahiqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDaftarMustahiqMouseExited
        // TODO add your handling code here:
        lblDaftarMustahiq.setForeground(Color.black);
    }//GEN-LAST:event_lblDaftarMustahiqMouseExited

    private void lblDaftarMustahiqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDaftarMustahiqMouseClicked
        // TODO add your handling code here:
        new mustahiq.daftarMustahiq().setVisible(true);
    }//GEN-LAST:event_lblDaftarMustahiqMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        nilai=0;
        txtBeras.setText(null);
        txtZakat.setText(null);
        txtTotalZakat.setText(null);
        spnJiwa.setModel(jmlJiwa);
        txtTerbilang.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnAboutActionPerformed

    private void mnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAboutMouseClicked
        // TODO add your handling code here:
        new formAbout(this,false).setVisible(true);
    }//GEN-LAST:event_mnAboutMouseClicked

    private void txtBerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBerasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTInformasi;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDaftarMustahiq;
    private javax.swing.JLabel lblDaftarMuzakki;
    private javax.swing.JLabel lblInputMustahiq;
    private javax.swing.JLabel lblInputMuzakki;
    private javax.swing.JMenu mnAbout;
    private javax.swing.JMenu mnKeluar;
    private javax.swing.JSpinner spnJiwa;
    private javax.swing.JTextField txtBeras;
    private javax.swing.JTextField txtTerbilang;
    private javax.swing.JTextField txtTotalZakat;
    private javax.swing.JTextField txtZakat;
    // End of variables declaration//GEN-END:variables
}
