/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package muzakki;

import aplikasizakat.koneksi;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SpinnerNumberModel;
import javax.swing.JOptionPane;
/**
 *
 * @author abdul hamid
 */
public class dataMuzakki extends javax.swing.JFrame {

    /**
     * Creates new form inputMuzakki
     */
    koneksi k=new koneksi();
    SpinnerNumberModel modelJiwa;
    int zakatUang=0,zakatBeras=0;
    public dataMuzakki() {
        initComponents();
        k.konek();
        getData();          
    }
    public void getData(){
        Integer value;
        Integer min=0;
        Integer max=20;
        Integer step=1; 
        String sql="select * from dt_muzakki where nomor='"+datfarMuzakki.noEdit+"'";

        try{
            k.st=k.conn.createStatement();
            k.rs=k.st.executeQuery(sql);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Load data gagal");
            return;
        }
         try {
            k.rs.next();
            txtTanggal.setText(k.rs.getString("tglInput").toString());
            txtNomor.setText(Integer.toString(k.rs.getInt("nomor")));
            txtNamaMuzakki.setText(k.rs.getString("namaMuzakki").toString().toUpperCase());
            value=k.rs.getInt("jmlJiwa");
            modelJiwa=new SpinnerNumberModel(value,min,max,step);
            txtAlamat.setText(k.rs.getString("Alamat").toString().toUpperCase());
            spinnerJiwa.setModel(modelJiwa);
            txtZakatFitrah.setText(Integer.toString(k.rs.getInt("jmlZakat")));
            txtBeras.setText(Integer.toString(k.rs.getInt("jmlBeras")));
            txtPanitia.setText(koneksi.username);
            zakatUang=k.rs.getInt("jmlZakat");
            zakatBeras=k.rs.getInt("jmlBeras");
         } catch (SQLException e) {
             //JOptionPane.showMessageDialog(null,"Data gagal di perbarui");
         }
    }
    
    public void setKosongkan(){
        txtNamaMuzakki.setText(null);
        txtAlamat.setText(null);
        spinnerJiwa.setModel(modelJiwa);
        txtZakatFitrah.setText(null);
        txtBeras.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        txtNomor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNamaMuzakki = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spinnerJiwa = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtZakatFitrah = new javax.swing.JTextField();
        txtBeras = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPanitia = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INPUT DATA MUZAKKI");
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText(".:: EDIT DATA MUZAKKI ::.");

        jLabel2.setText("TANGGAL");

        jLabel3.setText("NOMOR");

        txtTanggal.setEditable(false);
        txtTanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtNomor.setEditable(false);
        txtNomor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setText("NAMA");

        jLabel5.setText("ALAMAT");

        spinnerJiwa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerJiwaStateChanged(evt);
            }
        });

        jLabel6.setText("JIWA");

        jLabel7.setText("ORANG");

        jLabel8.setText("ZAKAT FITRAH");

        txtBeras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBerasMousePressed(evt);
            }
        });

        jLabel9.setText("Kg");

        jLabel11.setText("PANITIA");

        txtPanitia.setEditable(false);
        txtPanitia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnBatal.setText("BATAL");
        btnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/WZSAVE.jpg"))); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEdit.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(24, 24, 24)
                                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaMuzakki, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spinnerJiwa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBeras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addComponent(txtZakatFitrah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPanitia, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6)
                                .addComponent(spinnerJiwa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtZakatFitrah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBeras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtPanitia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNamaMuzakki, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinnerJiwaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerJiwaStateChanged
        // TODO add your handling code here:
        /*int jiwa=modelJiwa.getNumber().intValue();          
        total=jiwa*Integer.parseInt(txtZakatFitrah.getText());
        txtTotal.setText(Integer.toString(total));*/
    }//GEN-LAST:event_spinnerJiwaStateChanged

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtBerasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBerasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBerasMousePressed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int jiwa=modelJiwa.getNumber().intValue();
        
        if(Integer.parseInt(txtZakatFitrah.getText())<zakatUang){
            zakatUang=zakatUang-Integer.parseInt(txtZakatFitrah.getText());
            zakatUang=datfarMuzakki.totalUang-zakatUang;
        }else if(Integer.parseInt(txtZakatFitrah.getText())>zakatUang){
            zakatUang=Integer.parseInt(txtZakatFitrah.getText())-zakatUang;
            zakatUang=datfarMuzakki.totalUang+zakatUang;
        }else{
            zakatUang=datfarMuzakki.totalUang;
        }
        if(Integer.parseInt(txtBeras.getText())<zakatBeras){
            zakatBeras=zakatBeras-Integer.parseInt(txtBeras.getText());
            zakatBeras=datfarMuzakki.totalBeras-zakatBeras;
        }else if(Integer.parseInt(txtBeras.getText())>zakatBeras){
            zakatBeras=Integer.parseInt(txtBeras.getText())-zakatBeras;
            zakatBeras=datfarMuzakki.totalBeras+zakatBeras;
        }else{
            zakatBeras=datfarMuzakki.totalBeras;
        }
        String sql="Update dt_muzakki set namaMuzakki='"+txtNamaMuzakki.getText().toUpperCase()+
                    "',alamat='"+txtAlamat.getText()+
                    "',jmlJiwa='"+Integer.toString(jiwa)+
                    "',jmlZakat='"+txtZakatFitrah.getText()+
                    "',jmlBeras='"+txtBeras.getText()+
                    "',panitia='"+koneksi.username+"' where nomor='"+datfarMuzakki.noEdit+"'";
        String updateLog="update log_muzakki set totalUang='"+zakatUang+"',totalBeras='"+zakatBeras+"'";
    try{
        try{
            k.st=k.conn.createStatement();
            k.st.execute(sql);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Penyimpanan Gagal");
            setKosongkan();
            txtNamaMuzakki.requestFocus();
            return;
        }
        try{
            k.st=k.conn.createStatement();
            k.st.execute(updateLog);
            //JOptionPane.showMessageDialog(this, "Data Berhasil Di Update");
        }catch(SQLException e){
            //JOptionPane.showMessageDialog(this, "Gagal Di Update");
            return;
        }
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Edit");
            dispose();
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, "Gagal Di Edit");
    }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataMuzakki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataMuzakki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataMuzakki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataMuzakki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataMuzakki().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spinnerJiwa;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBeras;
    private javax.swing.JTextField txtNamaMuzakki;
    private javax.swing.JTextField txtNomor;
    private javax.swing.JTextField txtPanitia;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtZakatFitrah;
    // End of variables declaration//GEN-END:variables
}
