/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mustahiq;

import aplikasizakat.koneksi;
import com.sun.org.apache.bcel.internal.Constants;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SpinnerNumberModel;
import javax.swing.JOptionPane;
/**
 *
 * @author abdul hamid
 */
public class inputMustahiq extends javax.swing.JFrame {

    /**
     * Creates new form inputMuzakki
     */
    koneksi k=new koneksi();
    public static int nomor=0,jmlBeras;
    public static Integer total;
    public inputMustahiq() {
        initComponents();
        
        k.konek();
        String sql="select nomor from dt_mustahiq";

         try{
            k.st=k.conn.createStatement();
            k.rs=k.st.executeQuery(sql);
            try{
            k.rs.last();
                if(k.rs.last()==false){
                    nomor=nomor+1;
                }else{
                    nomor=k.rs.getInt("nomor")+1;
                }
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Gagal Query");
                return;
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Gagal mengambil nomor");
            return;
        }
        txtPanitia.setText(k.username.toUpperCase());
        txtNomor.setText(Integer.toString(nomor));
        
    }
    public void setKosongkan(){
        txtNamaMustahiq.setText(null);
        txtKet.setText(null);
        cmbGolongan.setSelectedIndex(0);
        txtAlamat.setText(null);
        txtJmlUang.setText(null);
        txtJmlBeras.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        txtNomor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNamaMustahiq = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtJmlUang = new javax.swing.JTextField();
        txtJmlBeras = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPanitia = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cmbGolongan = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKet = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INPUT DATA MUZAKKI");
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText(".:: PENYALURAN ZAKAT ::.");

        jLabel2.setText("TANGGAL");

        jLabel3.setText("NOMOR");

        txtTanggal.setEditable(false);
        txtTanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtNomor.setEditable(false);
        txtNomor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setText("PENERIMA");

        jLabel5.setText("ALAMAT");

        jLabel8.setText("JUMLAH UANG");

        txtJmlBeras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtJmlBerasMousePressed(evt);
            }
        });

        jLabel9.setText("Kg");

        jLabel11.setText("PANITIA");

        txtPanitia.setEditable(false);
        txtPanitia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnBatal.setText("KELUAR");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/WZSAVE.jpg"))); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel12.setText("GOLONGAN");

        cmbGolongan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- PILIH GOLONGAN --", "FAKIR MISKIN", "AMILIN", "RIQOB", "GHARIMIN", "MUALLAF", "FISABILILLAH", "IBNU SABIL" }));
        cmbGolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGolonganActionPerformed(evt);
            }
        });

        jLabel13.setText("JUMLAH BERAS");

        txtKet.setColumns(20);
        txtKet.setRows(5);
        jScrollPane1.setViewportView(txtKet);

        jLabel6.setText("KETERANGAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaMustahiq, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbGolongan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPanitia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatal))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtJmlBeras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9))
                                    .addComponent(txtJmlUang, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJmlUang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJmlBeras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPanitia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNamaMustahiq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(cmbGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnReset)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        if(txtNamaMustahiq.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nama Penerima Belum di Isi");
            txtNamaMustahiq.requestFocus();
        }else if(cmbGolongan.getSelectedIndex()==0 ){
            JOptionPane.showMessageDialog(null,"Golongan Belum di Pilih");
            cmbGolongan.requestFocus();
        }else if(txtAlamat.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Alamat Belum di Isi");
            txtAlamat.requestFocus();
        }else if(txtJmlUang.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Jumlah Uang Belum di Isi");
            txtJmlUang.requestFocus();
        }else if(Integer.parseInt(txtJmlUang.getText()) > daftarMustahiq.totUangMuzakki){
            JOptionPane.showMessageDialog(null,"Jumlah Uang Melebihi Jumlah Maksimal");
            txtJmlUang.requestFocus();
        }else if(Integer.parseInt(txtJmlUang.getText()) < 0){
            JOptionPane.showMessageDialog(null,"Jumlah Uang Harus Lebih Dari 0");
            txtJmlUang.requestFocus();
        }else{
            boolean proses=false;
            if(txtJmlBeras.getText().isEmpty()){
                jmlBeras=0;
                proses=true;
            }else if((!(txtJmlBeras.getText().isEmpty()))&& (Integer.parseInt(txtJmlBeras.getText()) > daftarMustahiq.totBerasMuzakki)){
                JOptionPane.showMessageDialog(null,"Jumlah Beras Melebihi Jumlah Maksimal");
                txtJmlBeras.requestFocus();
                proses=false;
            }else if((!(txtJmlBeras.getText().isEmpty()))&& (Integer.parseInt(txtJmlBeras.getText()) < 0)){
                JOptionPane.showMessageDialog(null,"Jumlah Beras Harus Lebih Dari 0");
                txtJmlBeras.requestFocus();
                proses=false;
            }else{
                jmlBeras=Integer.parseInt(txtJmlBeras.getText());
                proses=true;
            }
       if(proses==true){
            String sql="INSERT into dt_mustahiq (nomor,tglInput,gol,namaMustahiq,alamat,ket,jmlUang,jmlBeras,panitia) VALUE ("+
                           nomor+",'"+
                           txtTanggal.getText()+"','"+
                           cmbGolongan.getSelectedItem()+"','"+
                           txtNamaMustahiq.getText().toUpperCase()+"','"+
                           txtAlamat.getText()+"','"+
                           txtKet.getText()+"','"+
                           txtJmlUang.getText()+"','"+
                           jmlBeras+"','"+
                           koneksi.username+"')";
            try{
                k.st=k.conn.createStatement();
                k.st.execute(sql);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Penyimpanan Gagal");
                setKosongkan();
                txtNamaMustahiq.requestFocus();
                return;
            }
            JOptionPane.showMessageDialog(this,"Data Berhasil Disimpan");
            this.dispose();
            //new inputMustahiq().setVisible(true);
       }
        }
            
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        nomor=0;
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        setKosongkan();
    }//GEN-LAST:event_btnResetActionPerformed

    private void cmbGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGolonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGolonganActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        DateFormat dateFormat=new SimpleDateFormat("dd-MM-yyyy");
        Date date=new Date();
        txtTanggal.setText(dateFormat.format(date).toString());
    }//GEN-LAST:event_formWindowOpened

    private void txtJmlBerasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJmlBerasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlBerasMousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        nomor=0;
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputMustahiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputMustahiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputMustahiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputMustahiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputMustahiq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cmbGolongan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtJmlBeras;
    private javax.swing.JTextField txtJmlUang;
    private javax.swing.JTextArea txtKet;
    private javax.swing.JTextField txtNamaMustahiq;
    private javax.swing.JTextField txtNomor;
    private javax.swing.JTextField txtPanitia;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
